export const SubjectConstants = {
  ADD_SUBJECT: 'Ajouter un sujet',
  SEARCH_SUBJECT: 'Chercher un sujet ',
  FILTERS: 'Filtres',
  MASK_FILTER: 'Masquer les filtres',
  SHOW_FILTER: 'Afficher les filtres',

  VISIBLE_FILTER: 'Afficher les filtres',
  INVISIBLE_FILTER: 'Masquer les filtres',
  SUBJECT_TITLE: 'Titre',
  SUBJECT_DESCRIPTION: 'Description',
  SUBJECT_TYPE: 'Sélectionner un type',
  SUBJECT_NONE_CHOICE: 'None',
  SUBJECT_TECHNOLOGYS: 'Choisir une(des) technologie(s)',
  SUBJECT_DEPARTMENTS: 'Sélectionner un département',
  SUBJECT_ADD: 'Ajouter',
  SUBJECT_CANCEL: 'Annuler',
  SUBJECT_LEVELS: 'Sélectionner un niveau',
  FILTER: 'Filtrer',
  EDIT_SUBJECT: 'Modifier un sujet',
  SUBJECT_EDIT: 'Modifier',
  SUBJECT_DETAILS: 'Details de sujet',
  SUBJECT_DONE: 'Terminer',
  SUBJECT_DETAILS_TITLE: 'Titre :',
  SUBJECT_DETAILS_DESCRIPTION: 'Description : ',
  SUBJECT_DETAILS_TYPE: 'Type :',
  SUBJECT_DETAILS_TECHNOLOGYY: 'Technologie :',
  SUBJECT_DETAILS_PROPOSEDBY: 'Proposé par :',
  SUBJECT_DETAILS_DEPARTMENTS: 'Department :',
  SUBJECT_DETAILS_LEVEL: 'Niveau :',
  SUBJECT_DETAILS_STATUS: 'Statut :',
  VERIFY_SUBJECT: 'Verification de sujet',
  SUBJECT_VERIFY: 'Vérifier',
  CONFIRM_SUBJECT: 'Confirmation de sujet',
  SUBJECT_REFUSER: 'Refuser',
  SUBJECT_CONFIRMED: 'Confirmer',
  REMOVE_SUBJECT: 'Tu veux vraiment supprimer ce sujet ?',
  SUBJECT_REMOVED: 'Supprimer',
  CANCEL_SUBJECT: 'Tu veux vraiment annuler ce sujet ?',


};
